# Codebasics (Numpy & Pandas)

In [18]:
import numpy as np

In [19]:
a=np.arange(12).reshape(3,4)

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [22]:
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [23]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [24]:
for x in np.nditer(a,order='c'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [25]:
for x in np.nditer(a,order='f'):# f=fortran
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [26]:
for x in np.nditer(a,order='f',flags=['external_loop']):# f=fortran
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [27]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [28]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [29]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [30]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [31]:
c=np.arange(3,19,5).reshape(4,1)
c

array([[ 3],
       [ 8],
       [13],
       [18]])

In [32]:
for x,y in np.nditer([a,c]):
    print(x,y)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

# Pandas

In [4]:
import pandas as pd

In [15]:
df=pd.read_csv("C://Users//A//Student_marksheet_.csv")
df

id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81     62.0     49
1      2    Lemmie    Male   15       B       29       41     17.0     40
2      3     Danya  Female   14       C       12       87     16.0     96
3      4     Denna  Female   14       B       15       53     82.0     33
4      5   Jocelin    Male   14       A       43        6      3.0     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15     25.0     10
246  247       Rog  Female   13       B        1        4      NaN     65
247  248      Kaia    Male   15       B       93       48     82.0     44
248  249      Anni  Female   14       B       35       73     66.0     59
249  250  Fernande    Male   15       B       50        8     80.0     78

[250 rows x 9 columns]

In [16]:
df['Maths'].max()

100

In [17]:
df['English'].min()

1

In [18]:
 df['Name'][df['Maths']<=10]

19           Ashlan
57            Issie
62     Massimiliano
122        Brandise
130          Blisse
136          Ailene
138           Bevan
139           Ricky
156           Paten
164         Fidelia
173         Margaux
197           Carol
203          Nealon
223           Tabbi
225           Blake
245          Nickie
Name: Name, dtype: object

In [19]:
 df['Name'][df['English']>=90]

10          Dunn
20         Amery
26      Charmine
38          Adah
51        Rollie
61         Fanny
68           Nil
78      Rosalynd
80      Teresita
84         Brien
96      Adolphus
104      Jeannie
115       Shanie
122     Brandise
128         Susy
134      Humfrid
149        Inger
150       Herold
155        Sarah
171      Desmund
180      Davidde
200       Ruddie
208        Zenia
212    Evangelin
223        Tabbi
Name: Name, dtype: object

In [20]:
 df['Maths'].mean()

53.016

In [21]:
df['English'].mean()

47.98

In [22]:
df['Science'].mean()

51.44

In [23]:
df['History'].mean() # Null values are not consider

52.878151260504204

In [24]:
df.isnull().sum()

id          0
Name        0
Gender      0
Age         0
Section     0
Science     0
English     0
History    12
Maths       0
dtype: int64

In [25]:
df

id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81     62.0     49
1      2    Lemmie    Male   15       B       29       41     17.0     40
2      3     Danya  Female   14       C       12       87     16.0     96
3      4     Denna  Female   14       B       15       53     82.0     33
4      5   Jocelin    Male   14       A       43        6      3.0     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15     25.0     10
246  247       Rog  Female   13       B        1        4      NaN     65
247  248      Kaia    Male   15       B       93       48     82.0     44
248  249      Anni  Female   14       B       35       73     66.0     59
249  250  Fernande    Male   15       B       50        8     80.0     78

[250 rows x 9 columns]

In [26]:
df.fillna(0,inplace=True) #he fillna() method replaces the NULL values with a specified value.
df


id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81     62.0     49
1      2    Lemmie    Male   15       B       29       41     17.0     40
2      3     Danya  Female   14       C       12       87     16.0     96
3      4     Denna  Female   14       B       15       53     82.0     33
4      5   Jocelin    Male   14       A       43        6      3.0     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15     25.0     10
246  247       Rog  Female   13       B        1        4      0.0     65
247  248      Kaia    Male   15       B       93       48     82.0     44
248  249      Anni  Female   14       B       35       73     66.0     59
249  250  Fernande    Male   15       B       50        8     80.0     78

[250 rows x 9 columns]

In [27]:
df['History'].mean()  #sum/242

50.34

In [28]:
a=pd.read_csv("C://Users//A//temperature_.csv")
a

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [29]:
# Making DataFrame
School_data={
    'maths':[12,23,45,50],
    'science':[33,44,43,23]
}
r=pd.DataFrame(School_data)
r

maths  science
0     12       33
1     23       44
2     45       43
3     50       23

In [30]:
a.shape

(6, 4)

In [31]:
rows,column=a.shape

In [32]:
rows

6

In [33]:
column

4

In [34]:
a.head()

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [35]:
a.head(2)

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [36]:
a.tail(2)

Day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [37]:
a[2:4]

Day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow

In [38]:
a[:]

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [39]:
a.columns

Index(['Day', 'temperature', 'windspeed', 'event'], dtype='object')

In [40]:
a.Day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: Day, dtype: object

In [41]:
a.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [42]:
 a['event'] # also can use

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [43]:
type(a.event)

pandas.core.series.Series

In [44]:
a

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [45]:
a[['event','Day']]

event       Day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [46]:
a[['Day','event','windspeed']]

Day  event  windspeed
0  1/1/2017   Rain          6
1  1/2/2017  Sunny          7
2  1/3/2017   Snow          2
3  1/4/2017   Snow          7
4  1/5/2017   Rain          4
5  1/6/2017  Sunny          2

In [47]:
a.temperature

0    32
1    35
2    28
3    24
4    32
5    32
Name: temperature, dtype: int64

In [48]:
a.temperature.max()

35

In [49]:
a.temperature.min()

24

In [50]:
a.temperature.mean()

30.5

In [51]:
a.temperature.std()

3.8858718455450894

In [52]:
a.temperature.median()

32.0

In [53]:
a.describe() # Statistics

temperature  windspeed
count     6.000000   6.000000
mean     30.500000   4.666667
std       3.885872   2.338090
min      24.000000   2.000000
25%      29.000000   2.500000
50%      32.000000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

# Conditional select

In [54]:
a[a.windspeed>=5]

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
3  1/4/2017           24          7   Snow

In [55]:
a[a.windspeed==a['windspeed'].max()]

Day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
3  1/4/2017           24          7   Snow

In [56]:
a['Day'][a.windspeed==a['windspeed'].max()]

1    1/2/2017
3    1/4/2017
Name: Day, dtype: object

In [57]:
a[['Day','windspeed']][a.windspeed==a['windspeed'].max()]

Day  windspeed
1  1/2/2017          7
3  1/4/2017          7

In [58]:
a[['Day','temperature']][a.windspeed==a['windspeed'].max()]

Day  temperature
1  1/2/2017           35
3  1/4/2017           24

In [59]:
a

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [60]:
a.index

RangeIndex(start=0, stop=6, step=1)

# Changing Index

In [61]:
a.set_index('Day')

temperature  windspeed  event
Day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           32          2  Sunny

In [62]:
a

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [63]:
a.set_index('Day',inplace=True)

In [64]:
a

temperature  windspeed  event
Day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           32          2  Sunny

In [65]:
a.loc['1/1/2017']#Access a group of rows and columns by label(s) or a boolean array. .loc[] is primarily label based, but may also be used with a boolean array. 

temperature      32
windspeed         6
event          Rain
Name: 1/1/2017, dtype: object

In [66]:
# reset index
a.reset_index(inplace=True)
a

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [67]:
a.loc[2]

Day            1/3/2017
temperature          28
windspeed             2
event              Snow
Name: 2, dtype: object

In [68]:
# we become any column index

a.set_index('event',inplace=True)
a

Day  temperature  windspeed
event                                  
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           32          2

In [69]:
a.loc['Snow']

Day  temperature  windspeed
event                                  
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [70]:
a


Day  temperature  windspeed
event                                  
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           32          2

# Read the file like different differents types

In [71]:
import pandas as pd

In [72]:
# CSV
p=pd.read_csv("C://Users//A//temperature_.csv")
p

Day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           32          2  Sunny

In [73]:
# Excel
q=pd.read_excel("C://Users//A//temperature.xlsx","Sheet1")
q

Day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow
3 2017-01-04           24          7   Snow
4 2017-01-05           32          4   Rain
5 2017-01-06           32          2  Sunny

In [74]:
# creating d.f. using python dictionary
dict_={
    'day':[1,2,3,4,5],
    'ram':[13,67,7,90,88],
    'raghu':[22,33,45,55,78],
    'siya':['rr',33,456,"gh",66]
}
di=pd.DataFrame(dict_)
di

day  ram  raghu siya
0    1   13     22   rr
1    2   67     33   33
2    3    7     45  456
3    4   90     55   gh
4    5   88     78   66

In [75]:
# creating d.f. using python Tupels list
data=[
    ('1/2/2021',22,33,'rain'),
    ('2/2/2021',23,57,"Snow"),
    ('3/2/2021',26,78,'sun')
     # one tupel is denote one row
]
gk=pd.DataFrame(data,columns=['day',"temp",'winds','event'])
gk

day  temp  winds event
0  1/2/2021    22     33  rain
1  2/2/2021    23     57  Snow
2  3/2/2021    26     78   sun

In [76]:
# creating d.f. using python list of Dictionary
w=[
    {'day':'1/2/2020','temp':33,'wind':55,'event':'snow'},
    {'day':'2/2/2020','temp':73,'wind':5,'event':'rain'},
    {'day':'3/2/2020','temp':90,'wind':88,'event':'sun'}
]
gg=pd.DataFrame(w)
gg

day  temp  wind event
0  1/2/2020    33    55  snow
1  2/2/2020    73     5  rain
2  3/2/2020    90    88   sun

# video=4

In [77]:
#s=pd.read_csv("Book1.csv")
#s

In [78]:
#ss=pd.read_csv("Book1.csv",skiprows=1)
#ss  # use skiprows or header

In [79]:
#ss=pd.read_csv("Book1.csv",header=1) # header is start from 0
#ss

In [80]:
#d=pd.read_excel("Book2.xlsx",header=None)
#d

In [81]:
#d=pd.read_excel("Book2.xlsx",header=None,names=['name','rollno','maths','science','ss','total'])
#d

# read limited data from csv

In [82]:
#s=pd.read_csv("Book1.csv",skiprows=1,nrows=2)
#s

# Null Value

In [88]:
e=pd.read_excel("Book3.xlsx",header=1,na_values=["not available","n.a."])
e #NaN

Name  Roll No.  Maths  Science    ss  Total
0  Vora        12   66.0      NaN  59.0    125
1    gk        23   65.0     45.0  65.0    175
2    yk        36    NaN     68.0  75.0    143
3   raj        44   67.0     87.0   NaN    154

In [90]:
# IF we replce any minus values in NaN
f=pd.read_excel("Book3.xlsx",header=1,na_values=["not available","n.a.",-1])
f # -1 values ni jagya a NaN avi jay

Name  Roll No.  Maths  Science    ss  Total
0  Vora        12   66.0      NaN  59.0    125
1    gk        23   65.0     45.0  65.0    175
2    yk        36    NaN     68.0  75.0    143
3   raj        44   67.0     87.0   NaN    154

# video = 05

In [138]:
e1=pd.read_excel("TEM.xlsx")
e1 #

Day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04         35.0        7.0    NaN
2 2017-01-06          NaN        NaN   Snow
3 2017-01-09         24.0        7.0    NaN
4 2017-01-13         32.0        NaN   Rain
5 2017-01-18          NaN        2.0  Sunny
6 2017-01-21          NaN        NaN    NaN
7 2017-01-28         22.0        NaN   Snow
8 2017-01-30         33.0        5.0    NaN

In [139]:
type(e1.Day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [140]:
# Converting string into data type
df=pd.read_excel("TEM.xlsx",parse_dates=["Day"]) 
df

Day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04         35.0        7.0    NaN
2 2017-01-06          NaN        NaN   Snow
3 2017-01-09         24.0        7.0    NaN
4 2017-01-13         32.0        NaN   Rain
5 2017-01-18          NaN        2.0  Sunny
6 2017-01-21          NaN        NaN    NaN
7 2017-01-28         22.0        NaN   Snow
8 2017-01-30         33.0        5.0    NaN

In [141]:
type(df.Day[0]) 

pandas._libs.tslibs.timestamps.Timestamp

In [142]:
df=pd.read_excel("TEM.xlsx") 
df.set_index("Day",inplace=True)
df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-06          NaN        NaN   Snow
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-21          NaN        NaN    NaN
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [143]:
new_df=df.fillna(0)
new_df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0      0
2017-01-06          0.0        0.0   Snow
2017-01-09         24.0        7.0      0
2017-01-13         32.0        0.0   Rain
2017-01-18          0.0        2.0  Sunny
2017-01-21          0.0        0.0      0
2017-01-28         22.0        0.0   Snow
2017-01-30         33.0        5.0      0

In [144]:
New_df=df.fillna({
    'temperature':0,
    'windspeed':0,
    'event':'No event'
})
New_df

temperature  windspeed     event
Day                                         
2017-01-01         32.0        6.0      Rain
2017-01-04         35.0        7.0  No event
2017-01-06          0.0        0.0      Snow
2017-01-09         24.0        7.0  No event
2017-01-13         32.0        0.0      Rain
2017-01-18          0.0        2.0     Sunny
2017-01-21          0.0        0.0  No event
2017-01-28         22.0        0.0      Snow
2017-01-30         33.0        5.0  No event

In [145]:
# if we put near values instead of 0 then
new__df=df.fillna(method='ffill') #forward fill
new__df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0   Rain
2017-01-06         35.0        7.0   Snow
2017-01-09         24.0        7.0   Snow
2017-01-13         32.0        7.0   Rain
2017-01-18         32.0        2.0  Sunny
2017-01-21         32.0        2.0  Sunny
2017-01-28         22.0        2.0   Snow
2017-01-30         33.0        5.0   Snow

In [146]:
new6df=df.fillna(method='bfill') #backward fill
new6df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0   Snow
2017-01-06         24.0        7.0   Snow
2017-01-09         24.0        7.0   Rain
2017-01-13         32.0        2.0   Rain
2017-01-18         22.0        2.0  Sunny
2017-01-21         22.0        5.0   Snow
2017-01-28         22.0        5.0   Snow
2017-01-30         33.0        5.0    NaN

In [147]:
df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-06          NaN        NaN   Snow
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-21          NaN        NaN    NaN
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [148]:
new6df=df.fillna(method='bfill',axis="columns") #axis
new6df

temperature windspeed  event
Day                                    
2017-01-01        32.0       6.0   Rain
2017-01-04        35.0       7.0    NaN
2017-01-06        Snow      Snow   Snow
2017-01-09        24.0       7.0    NaN
2017-01-13        32.0      Rain   Rain
2017-01-18         2.0       2.0  Sunny
2017-01-21         NaN       NaN    NaN
2017-01-28        22.0      Snow   Snow
2017-01-30        33.0       5.0    NaN

In [149]:
# limit parameter in fillna()
new__df=df.fillna(method='ffill',limit=1) 
new__df


temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0   Rain
2017-01-06         35.0        7.0   Snow
2017-01-09         24.0        7.0   Snow
2017-01-13         32.0        7.0   Rain
2017-01-18         32.0        2.0  Sunny
2017-01-21          NaN        2.0  Sunny
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0   Snow

In [150]:
new__df=df.fillna(method='ffill',limit=2) 
new__df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0   Rain
2017-01-06         35.0        7.0   Snow
2017-01-09         24.0        7.0   Snow
2017-01-13         32.0        7.0   Rain
2017-01-18         32.0        2.0  Sunny
2017-01-21         32.0        2.0  Sunny
2017-01-28         22.0        2.0   Snow
2017-01-30         33.0        5.0   Snow

In [151]:
df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-06          NaN        NaN   Snow
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-21          NaN        NaN    NaN
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [152]:
dff=df.interpolate()
dff

temperature  windspeed  event
Day                                      
2017-01-01    32.000000        6.0   Rain
2017-01-04    35.000000        7.0    NaN
2017-01-06    29.500000        7.0   Snow
2017-01-09    24.000000        7.0    NaN
2017-01-13    32.000000        4.5   Rain
2017-01-18    28.666667        2.0  Sunny
2017-01-21    25.333333        3.0    NaN
2017-01-28    22.000000        4.0   Snow
2017-01-30    33.000000        5.0    NaN

In [153]:
dfff=df.interpolate(method='time')
dfff

temperature  windspeed  event
Day                                      
2017-01-01    32.000000   6.000000   Rain
2017-01-04    35.000000   7.000000    NaN
2017-01-06    30.600000   7.000000   Snow
2017-01-09    24.000000   7.000000    NaN
2017-01-13    32.000000   4.777778   Rain
2017-01-18    28.666667   2.000000  Sunny
2017-01-21    26.666667   2.750000    NaN
2017-01-28    22.000000   4.500000   Snow
2017-01-30    33.000000   5.000000    NaN

In [154]:
# Drop all rows which have nan values
g=df.dropna()
g

temperature  windspeed event
Day                                     
2017-01-01         32.0        6.0  Rain

In [156]:
gk=df.dropna(how="all")
gk # 21 jan is missing which have all nan values

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-06          NaN        NaN   Snow
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [159]:
df

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-06          NaN        NaN   Snow
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-21          NaN        NaN    NaN
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [157]:
# thresh= at least one non nan values
gk1=df.dropna(thresh=1)
gk1 

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-06          NaN        NaN   Snow
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [158]:
gk2=df.dropna(thresh=2)
gk2 

temperature  windspeed  event
Day                                      
2017-01-01         32.0        6.0   Rain
2017-01-04         35.0        7.0    NaN
2017-01-09         24.0        7.0    NaN
2017-01-13         32.0        NaN   Rain
2017-01-18          NaN        2.0  Sunny
2017-01-28         22.0        NaN   Snow
2017-01-30         33.0        5.0    NaN

In [160]:
# how to fill missing date
dt=pd.date_range('01-01-2017','01-30-2017')
idx=pd.DatetimeIndex(dt)
df.reindex(idx)

temperature  windspeed  event
2017-01-01         32.0        6.0   Rain
2017-01-02          NaN        NaN    NaN
2017-01-03          NaN        NaN    NaN
2017-01-04         35.0        7.0    NaN
2017-01-05          NaN        NaN    NaN
2017-01-06          NaN        NaN   Snow
2017-01-07          NaN        NaN    NaN
2017-01-08          NaN        NaN    NaN
2017-01-09         24.0        7.0    NaN
2017-01-10          NaN        NaN    NaN
2017-01-11          NaN        NaN    NaN
2017-01-12          NaN        NaN    NaN
2017-01-13         32.0        NaN   Rain
2017-01-14          NaN        NaN    NaN
2017-01-15          NaN        NaN    NaN
2017-01-16          NaN        NaN    NaN
2017-01-17          NaN        NaN    NaN
2017-01-18          NaN        2.0  Sunny
2017-01-19          NaN        NaN    NaN
2017-01-20          NaN        NaN    NaN
2017-01-21          NaN        NaN    NaN
2017-01-22          NaN        NaN    NaN
2017-01-23          NaN        NaN    NaN
2017-01-24          NaN        NaN    NaN
2017-01-25          NaN        NaN    NaN
2017-01-26          NaN        NaN    NaN
2017-01-27          NaN        NaN    NaN
2017-01-28         22.0        NaN   Snow
2017-01-29          NaN        NaN    NaN
2017-01-30         33.0        5.0    NaN