In [5]:
import numpy as np

In [5]:
# Using List
b=[2,3,4,5,6,7]
c=np.array(b)
c

array([1, 2, 3, 4, 5])

In [21]:
# Using Tuple
A=(1,2,3,4,5)
j=np.array(A)
g=np.array((1,2,3,4))
print(j,g)

[1 2 3 4 5] [1 2 3 4]


In [12]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
d=np.array([[1,2],[3,4]])
print(d)

[[1 2]
 [3 4]]


In [16]:
e=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
r=np.array([12,3,44,5],"float")
w=np.array([12,3,44,5],"int")
q=np.array([12,3,44,5],"complex")
print(r,w,q)

[12.  3. 44.  5.] [12  3 44  5] [12.+0.j  3.+0.j 44.+0.j  5.+0.j]


In [24]:
## Arange                         #help(np.arange)
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
c=np.arange(1,10)
c                    # 10 is Exclusive

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x=np.arange(10.0)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.arange(10,dtype="float")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
np.arange(1,10,2,dtype="complex")

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j, 9.+0.j])

In [ ]:
## Zeros

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros(3,dtype="int")

array([0, 0, 0])

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.zeros([3,4],order='C')


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.zeros([3,4],order="f")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
## Ones and Empty

In [49]:
np.ones(3)

array([1., 1., 1.])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones([2,3],dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
np.ones([2,3],order="f")

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [63]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.empty([3,4],dtype="int")

array([[         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248]])

In [64]:
## Linspace

In [66]:
np.linspace(1,10) # bydeduat taking 50 values

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [67]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [68]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [70]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [71]:
np.linspace(1,100,4,dtype="int")

array([  1,  34,  67, 100])

In [73]:
## Eye   Identity Matrix or unit matrix

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [78]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [80]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [81]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.eye(5,k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
## Random

In [85]:
# rand
np.random.rand(5)

array([0.93590652, 0.21717569, 0.41403575, 0.31045526, 0.56746103])

In [87]:
np.rand(5)

In [89]:
np.random.rand(2,3)

array([[0.84644456, 0.96993924, 0.42777532],
       [0.6721832 , 0.3107589 , 0.27341136]])

In [100]:
# randn    (n=normal distribution)
np.random.randn(5)

array([ 0.38703867,  0.32501241, -1.56854116, -1.11688005,  1.14572092])

In [101]:
np.random.randn(2,3)

array([[-1.06791015,  0.74819623,  0.67411147],
       [ 1.38694261, -0.9364473 ,  1.66709553]])

In [105]:
# ranf   (f=floating value in (0,1))
np.random.ranf(5)

array([0.96418927, 0.75304717, 0.94185933, 0.37750906, 0.73936529])

In [109]:
np.random.ranf((2,3))

array([[0.34796335, 0.89498164, 0.31455453],
       [0.7723282 , 0.25188288, 0.01676604]])

In [116]:
# randint    (integer)   less than (n)
np.random.randint(2)

0

In [ ]:
np.random.randint(0)

In [127]:
np.random.randint((1,3,5))

array([0, 0, 4])

# Attributes of Array

In [33]:
a=np.array([1,2,3,4])
b=np.array([[1,2],[3,4]])
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [34]:
a

array([1, 2, 3, 4])

In [35]:
b

array([[1, 2],
       [3, 4]])

In [36]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
# ndim
print(a.ndim,b.ndim,c.ndim)

1 2 3


In [38]:
# shape
print(a.shape,b.shape,c.shape)

(4,) (2, 2) (1, 3, 3)


In [39]:
# Size   (product of raw and column (gives total no. of element))
print(a.size,b.size,c.size)

4 4 9


In [40]:
## Dtype
d=np.array([1,2,3],"float")
print(d.dtype)
print(a.dtype)

#### By default data type if float64

float64
int32


In [41]:
## Itemsize
print(a.itemsize,b.itemsize,c.itemsize)   # int32,,,,32/8=4 bytes

4 4 4


In [42]:
## Indexing

In [43]:
a

array([1, 2, 3, 4])

In [44]:
b

array([[1, 2],
       [3, 4]])

In [45]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
a[1]

2

In [47]:
b[0]

array([1, 2])

In [48]:
b[0][1]

2

In [52]:
c[0][1][2]

6

In [54]:
c[0][0][2]

3

In [62]:
e=np.array([[[1,2,3],[11,22,33],[4,5,6]],[[44,55,66],[7,8,9],[77,88,99]]])
e

array([[[ 1,  2,  3],
        [11, 22, 33],
        [ 4,  5,  6]],

       [[44, 55, 66],
        [ 7,  8,  9],
        [77, 88, 99]]])

In [63]:
e[1][1][2]

9

In [64]:
e[0][1][2]

33

In [65]:
f=np.array([[[1,2,3],[11,22,33],[4,5,6]],[[44,55,66],[7,8,9],[77,88,99]],[[23,34,45],[12,21,23],[54,45,66]]])
f

array([[[ 1,  2,  3],
        [11, 22, 33],
        [ 4,  5,  6]],

       [[44, 55, 66],
        [ 7,  8,  9],
        [77, 88, 99]],

       [[23, 34, 45],
        [12, 21, 23],
        [54, 45, 66]]])

In [66]:
f[2][2][1]

45

In [67]:
## Slicing

In [68]:
a

array([1, 2, 3, 4])

In [77]:
B=np.array([[1, 2],[3, 4],[4,5]])
B

array([[1, 2],
       [3, 4],
       [4, 5]])

In [70]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [71]:
a[0:2]

array([1, 2])

In [72]:
a[1:3]

array([2, 3])

In [78]:
B[:,:]

array([[1, 2],
       [3, 4],
       [4, 5]])

In [79]:
B[:1,:]

array([[1, 2]])

In [81]:
B[2:,1:]

array([[5]])

In [82]:
f

array([[[ 1,  2,  3],
        [11, 22, 33],
        [ 4,  5,  6]],

       [[44, 55, 66],
        [ 7,  8,  9],
        [77, 88, 99]],

       [[23, 34, 45],
        [12, 21, 23],
        [54, 45, 66]]])

In [83]:
f[:2,1:2,0:1]

array([[[11]],

       [[ 7]]])

In [84]:
f[1:2,0:2,1:3]

array([[[55, 66],
        [ 8,  9]]])

In [85]:
## Arithmetic Operation

In [86]:
a

array([1, 2, 3, 4])

In [87]:
b

array([[1, 2],
       [3, 4]])

In [88]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [89]:
a+2

array([3, 4, 5, 6])

In [90]:
a-1

array([0, 1, 2, 3])

In [91]:
a*2


array([2, 4, 6, 8])

In [92]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [93]:
c+1

array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [94]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [95]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [96]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [100]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,5])
print(A)
print(B)

[1 2 3 4 5]
[6 7 8 9 5]


In [98]:
A+B

array([ 7,  9, 11, 13, 10])

In [101]:
A*B

array([ 6, 14, 24, 36, 25])

In [102]:
A-B

array([-5, -5, -5, -5,  0])

In [103]:
A/B

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 1.        ])

In [105]:
C=b
C

array([[1, 2],
       [3, 4]])

In [107]:
D=np.array([[22,11],[1,2]])
D

array([[22, 11],
       [ 1,  2]])

In [108]:
C+D

array([[23, 13],
       [ 4,  6]])

In [109]:
C*D

array([[22, 22],
       [ 3,  8]])

In [110]:
## Also Usinf Function

In [111]:
np.add(A,B)

array([ 7,  9, 11, 13, 10])

In [114]:
np.subtract(A,B)

array([-5, -5, -5, -5,  0])

In [116]:
np.multiply(A,B)

array([ 6, 14, 24, 36, 25])

In [117]:
np.divide(A,B)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 1.        ])

In [118]:
np.mod(A,B)

array([1, 2, 3, 4, 0], dtype=int32)

In [119]:
np.power(A,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [120]:
### Reshape

In [121]:
a

array([1, 2, 3, 4])

In [122]:
b

array([[1, 2],
       [3, 4]])

In [124]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [125]:
print(a.shape,b.shape,c.shape)

(4,) (2, 2) (1, 3, 3)


In [127]:
q=np.reshape(a,(2,2))
q

array([[1, 2],
       [3, 4]])

In [131]:
w=np.arange(1,20,2)
w

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [134]:
print(np.reshape(w,(5,2)))
print(np.reshape(w,(10,1)))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]]


In [137]:
## Resize

In [138]:
a

array([1, 2, 3, 4])

In [139]:
b

array([[1, 2],
       [3, 4]])

In [141]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [142]:
print(a.size,b.size,c.size)

4 4 9


In [143]:
print(np.resize(a,(3,3)))

[[1 2 3]
 [4 1 2]
 [3 4 1]]


In [146]:
print(np.resize(a,(2,2)))

[[1 2]
 [3 4]]


In [144]:
print(np.resize(b,(5,5)))

[[1 2 3 4 1]
 [2 3 4 1 2]
 [3 4 1 2 3]
 [4 1 2 3 4]
 [1 2 3 4 1]]


In [145]:
print(np.resize(c,(2,2)))

[[1 2]
 [3 4]]


In [147]:
# convert into one dimensional 1-D
c.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
b.flatten()

array([1, 2, 3, 4])

In [153]:
c.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
b.ravel()

array([1, 2, 3, 4])

In [155]:
a.ravel()

array([1, 2, 3, 4])

In [156]:
## Ravel is FAster than flattne

In [157]:
## Transpose

In [158]:
a

array([1, 2, 3, 4])

In [159]:
b

array([[1, 2],
       [3, 4]])

In [166]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [170]:
dd=np.transpose(a)

ff=np.transpose(b)

vv=np.transpose(c)

In [171]:
dd

array([1, 2, 3, 4])

In [172]:
ff

array([[1, 3],
       [2, 4]])

In [173]:
vv

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [174]:
a

array([1, 2, 3, 4])

In [175]:
b

array([[1, 2],
       [3, 4]])

In [176]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [181]:
np.swapaxes(b,0,1)

array([[1, 3],
       [2, 4]])

In [182]:
np.swapaxes(b,1,0)

array([[1, 3],
       [2, 4]])

In [185]:
np.swapaxes(c,1,2)

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [197]:
## concatenate

In [186]:
A

array([1, 2, 3, 4, 5])

In [187]:
B

array([6, 7, 8, 9, 5])

In [192]:
np.concatenate((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5])

In [193]:
C

array([[1, 2],
       [3, 4]])

In [194]:
D

array([[22, 11],
       [ 1,  2]])

In [196]:
np.concatenate((D,C))

array([[22, 11],
       [ 1,  2],
       [ 1,  2],
       [ 3,  4]])

In [198]:
# Split

In [199]:
C

array([[1, 2],
       [3, 4]])

In [203]:
f

array([[[ 1,  2,  3],
        [11, 22, 33],
        [ 4,  5,  6]],

       [[44, 55, 66],
        [ 7,  8,  9],
        [77, 88, 99]],

       [[23, 34, 45],
        [12, 21, 23],
        [54, 45, 66]]])

In [213]:
np.split(f,3)

[array([[[ 1,  2,  3],
         [11, 22, 33],
         [ 4,  5,  6]]]),
 array([[[44, 55, 66],
         [ 7,  8,  9],
         [77, 88, 99]]]),
 array([[[23, 34, 45],
         [12, 21, 23],
         [54, 45, 66]]])]